version: '3.4'

services:
  bds:
    image: itzg/minecraft-server
    environment:
      EULA: 'TRUE'
      GAMEMODE: survival
      DIFFICULTY: normal
    ports:
      - 25565:25565/tcp
    volumes:
      - bds:/data
    container_name: bds

volumes:
  bds: {}